export const DEFAULT_CLAUDE_MD = `# AI Assistant Context

## Project: {{project_name}}

**Tech Stack:** {{tech_stack}}

## Guidelines

- Write clean, idiomatic TypeScript
- Prefer functional patterns and immutability
- Always handle errors explicitly
- Write tests for non-trivial logic

## Project Structure

<!-- Describe your project structure here -->

## Common Patterns

<!-- Document recurring patterns and conventions here -->

_Generated by Aide on {{date}}_
`

export const DEFAULT_AGENTS_MD = `# AI Agents

## Default Agent

**Role:** General-purpose coding assistant for {{project_name}}

**Tech Stack:** {{tech_stack}}

**Capabilities:**
- Code review and refactoring
- Bug diagnosis and fixing
- Architecture guidance
- Test generation

_Generated by Aide on {{date}}_
`

export const DEFAULT_CURSORRULES = `# Cursor Rules for {{project_name}}

## Tech Stack
{{tech_stack}}

## Code Style
- Use TypeScript strict mode
- Prefer \`const\` over \`let\`
- Use descriptive variable names
- Keep functions small and focused

## Generated by Aide on {{date}}
`

export const DEFAULT_TEMPLATES: Record<string, string> = {
  'CLAUDE.md': DEFAULT_CLAUDE_MD,
  'AGENTS.md': DEFAULT_AGENTS_MD,
  '.cursorrules': DEFAULT_CURSORRULES,
}
