/** IPC channel names shared between main and renderer */
export const IPC = {
  INIT: 'aide:init',
  ADD: 'aide:add',
  REMOVE: 'aide:remove',
  APPLY: 'aide:apply',
  LIST: 'aide:list',
  LINK: 'aide:link',
  UNLINK: 'aide:unlink',
  SYNC: 'aide:sync',
  READ_REGISTRY: 'aide:readRegistry',
  READ_CONFIG: 'aide:readConfig',
  UPDATE_CONFIG: 'aide:updateConfig',
  DISCOVER: 'aide:discover',
  PICK_FOLDER: 'aide:pickFolder',
  LIST_PROJECT_SKILLS:   'aide:listProjectSkills',
  DISABLE_PROJECT_SKILL: 'aide:disableProjectSkill',
  ENABLE_PROJECT_SKILL:  'aide:enableProjectSkill',
  IMPORT_PROJECT_SKILL:  'aide:importProjectSkill',
  COPY_PROJECT_SKILL:    'aide:copyProjectSkill',
  READ_SKILL_FRONTMATTER: 'aide:readSkillFrontmatter',
  IS_INITIALIZED: 'aide:isInitialized',
  LIST_REMOTE_SKILLS: 'aide:listRemoteSkills',
  ADD_REMOTE_SKILL: 'aide:addRemoteSkill',
  OPEN_EXTERNAL: 'aide:openExternal',

  // Phase 4 additions
  READ_MOD_CONTENT:          'aide:readModContent',
  WRITE_MOD_CONTENT:         'aide:writeModContent',
  LIST_MARKETPLACE_SKILLS:   'aide:listMarketplaceSkills',
  LIST_SKILLSSH_PACKAGES:    'aide:listSkillsShPackages',
  INSTALL_SKILLSSH_PACKAGE:  'aide:installSkillsShPackage',
} as const
