/** IPC channel names shared between main and renderer */
export const IPC = {
  INIT: 'aide:init',
  ADD: 'aide:add',
  REMOVE: 'aide:remove',
  APPLY: 'aide:apply',
  LIST: 'aide:list',
  LINK: 'aide:link',
  UNLINK: 'aide:unlink',
  SYNC: 'aide:sync',
  READ_REGISTRY: 'aide:readRegistry',
  READ_CONFIG: 'aide:readConfig',
  UPDATE_CONFIG: 'aide:updateConfig',
  DISCOVER: 'aide:discover',
  PICK_FOLDER: 'aide:pickFolder',
  LIST_PROJECT_SKILLS:   'aide:listProjectSkills',
  DISABLE_PROJECT_SKILL: 'aide:disableProjectSkill',
  ENABLE_PROJECT_SKILL:  'aide:enableProjectSkill',
  IMPORT_PROJECT_SKILL:  'aide:importProjectSkill',
  COPY_PROJECT_SKILL:    'aide:copyProjectSkill',
  READ_SKILL_FRONTMATTER: 'aide:readSkillFrontmatter',
  IS_INITIALIZED: 'aide:isInitialized',
} as const
